### ISSUE TITLE
Using HolidaySystem creates error -> Could not load file or assembly System.Memory, Version=4.0.1.2

### ISSUE THREAD

**Issue by mytechmicke** [nager/Nager.Date#626]
### NuGet Package Version

2.2.2

### More information

Hi,
Stack trace in my project:

   at Nager.LicenseSystem.LicenseKeyValidator.Validate(String licenseKey, LicenseInfo& licenseInfo)
   at Nager.Date.Helpers.LicenseHelper.CheckLicenseKey(String licenseKey)
   at Nager.Date.HolidaySystem.CheckLicense(String licenseKey)
   at Nager.Date.HolidaySystem.TryGetHolidayProvider(CountryCode countryCode, IHolidayProvider& holidayProvider)
   at Nager.Date.HolidaySystem.IsHoliday(DateTime date, CountryCode countryCode, HolidayTypes holidayTypes, Holiday[]& publicHolidays)
   at BookingSentinel.CalendarHelper.IsDayHoliday(DateTime day) in C:\Users\Micke\Documents\Visual Studio 2022\Projects\BookingFactory\BookingFactory\BookingSentinel\CalendarHelper.cs:line 85
   at BookingSentinel.CalendarHelper.IsDayWorkDay(DateTime day) in C:\Users\Micke\Documents\Visual Studio 2022\Projects\BookingFactory\BookingFactory\BookingSentinel\CalendarHelper.cs:line 64
   at BookingSentinel.CalendarHelper.AdjustStopDateForHolidaysAndWeekends(DateTime start, DateTime stop) in C:\Users\Micke\Documents\Visual Studio 2022\Projects\BookingFactory\BookingFactory\BookingSentinel\CalendarHelper.cs:line 538
   at BookingSentinel.BookingSentinel.OnSaving(IBooking item) in C:\Users\Micke\Documents\Visual Studio 2022\Projects\BookingFactory\BookingFactory\BookingSentinel\BookingSentinel.cs:line 158
   
and also:
 
   {"Could not load file or assembly 'System.Memory, Version=4.0.1.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. 
   The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)":"System.Memory, Version=4.0.1.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51"}

This occurs when using HolidaySystem.
I have set license key both in function and in creation of class.
What is wrong here?
Best regards,
Mikael

**Comment by mytechmicke** [comment]
Hi,
4.7.2

**Comment by tinohager** [comment]
I have test it with a fresh 4.7.2 project without issues.

Can you try this to your `app.config`

```
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Memory" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-4.5.5" newVersion="4.5.5" />
      </dependentAssembly>
    </assemblyBinding>
```

https://github.com/confluentinc/confluent-kafka-dotnet/issues/1507#issuecomment-961521387

**Comment by mytechmicke** [comment]
Hi,
Now the file looks like this:

<?xml version="1.0" encoding="utf-8"?>
<configuration>
                             <runtime>
                                                          <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
                                                                                       <dependentAssembly>
                                                                                                                    <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
                                                                                                                    <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
                                                                                       </dependentAssembly>
                                                                                       <dependentAssembly>
                                                                                                                    <assemblyIdentity name="System.Memory" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral"/>
                                                                                                                    <bindingRedirect oldVersion="0.0.0.0-4.5.5" newVersion="4.5.5" />
                                                                                       </dependentAssembly>
                                                          </assemblyBinding>
                             </runtime>
</configuration>

Is this correct?
This did not work, same error.
Best regards,
Mikael

**Comment by tinohager** [comment]
Can you validate this in your project file? (.csproj)

`<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>`

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    ....
  </PropertyGroup>
```

**Comment by mytechmicke** [comment]
Hi, 
Same error. I will try on another machine/project.

**Comment by mytechmicke** [comment]
Hi,
Exactly same error on a different machine and another project.

**Comment by tinohager** [comment]
Do you have the same error with a clean new .net 4.7.2 project?

**Comment by mytechmicke** [comment]
Hi,
I made a new WinForm project and there it works.
My other projects are of type Class Library. It does not work in any of them.
Can you see any differences between project types that might affect the functions and create this error?

**Comment by mytechmicke** [comment]
Hi,
I have done a chart over which dll's are used, enclosed pdf file. The one called Mobigo is the software that I'm extending and the columns shows which dll's are used and what version. In Nager column I have the versions from install, see enclosed image.
Do you see any problems with the different versions?
[Nager-Mobigo-files-versions.pdf](https://github.com/nager/Nager.Date/files/14772661/Nager-Mobigo-files-versions.pdf)
![NagerInstall](https://github.com/nager/Nager.Date/assets/32257833/5b2cec7b-5599-43ca-be3c-241e6584a24c)

**Comment by mytechmicke** [comment]
Hi,
I tried to overwrite all common DLL's (used all from Nager) and got a different error:

   at System.ReadOnlySpan`1..ctor(T[] array)
   at Nager.LicenseSystem.LicenseKeyValidator.Validate(String licenseKey, LicenseInfo& licenseInfo)
   at Nager.Date.Helpers.LicenseHelper.CheckLicenseKey(String licenseKey)
   at Nager.Date.HolidaySystem.CheckLicense(String licenseKey)
   at Nager.Date.HolidaySystem.TryGetHolidayProvider(CountryCode countryCode, IHolidayProvider& holidayProvider)
   at Nager.Date.HolidaySystem.IsHoliday(DateTime date, CountryCode countryCode, HolidayTypes holidayTypes, Holiday[]& publicHolidays)
   at BookingSentinel.CalendarHelper.IsDayHoliday(DateTime day) in C:\Users\Micke\Documents\Visual Studio 2022\Projects\BookingFactory\BookingFactory\BookingSentinel\CalendarHelper.cs:line 87
   at BookingSentinel.CalendarHelper.IsDayWorkDay(DateTime day) in C:\Users\Micke\Documents\Visual Studio 2022\Projects\BookingFactory\BookingFactory\BookingSentinel\CalendarHelper.cs:line 64
   at BookingSentinel.CalendarHelper.AdjustStopDateForHolidaysAndWeekends(DateTime start, DateTime stop) in C:\Users\Micke\Documents\Visual Studio 2022\Projects\BookingFactory\BookingFactory\BookingSentinel\CalendarHelper.cs:line 542
   at BookingSentinel.BookingSentinel.OnSaving(IBooking item) in C:\Users\Micke\Documents\Visual Studio 2022\Projects\BookingFactory\BookingFactory\BookingSentinel\BookingSentinel.cs:line 158
   
   Could not load file or assembly '**System.Runtime.CompilerServices.Unsafe**, Version=4.0.6.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
   The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by tinohager** [comment]
> Hi, The only json part in my projects is: Newtonsoft.json >= 12.0.1 Can this be a problem?

it may also be another package which in turn has a dependency on system.text.json.

**Comment by tinohager** [comment]
> Hi, I made a new WinForm project and there it works. My other projects are of type Class Library. It does not work in any of them. Can you see any differences between project types that might affect the functions and create this error?

This Setup work on my test, `Class1.cs` contains the `Nager.Date logic`
![image](https://github.com/nager/Nager.Date/assets/8215186/31566e25-2259-4296-83d6-2bbb939381e4)

**Comment by tinohager** [comment]
> Hi, I have done a chart over which dll's are used, enclosed pdf file. The one called Mobigo is the software that I'm extending and the columns shows which dll's are used and what version. In Nager column I have the versions from install, see enclosed image. Do you see any problems with the different versions? [Nager-Mobigo-files-versions.pdf](https://github.com/nager/Nager.Date/files/14772661/Nager-Mobigo-files-versions.pdf) ![NagerInstall](https://private-user-images.githubusercontent.com/32257833/317250122-5b2cec7b-5599-43ca-be3c-241e6584a24c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NDk2OTQsIm5iZiI6MTcxMTU0OTM5NCwicGF0aCI6Ii8zMjI1NzgzMy8zMTcyNTAxMjItNWIyY2VjN2ItNTU5OS00M2NhLWJlM2MtMjQxZTY1ODRhMjRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDE0MjMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMTBjMGIwYzNmNDkwMDc5NzMwZjMzZmZhY2RhODBmOTk1MjQyNjhiMDJlNDk4YWMxYzZmMGQ1YzcxNWI5OWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KwFHv_lLNFtXq8TULpySEo7m8Hu3EmEXATTwEZUgPro)

The versions in the pdf make no sense, these versions do not exist according to nuget.org
![image](https://github.com/nager/Nager.Date/assets/8215186/1154d359-8ff6-4470-be3d-38b8352e27cd)

**Comment by tinohager** [comment]
how can i reach you best do you want to send me an e-mail?

**Comment by mytechmicke** [comment]
Hi,
mikael@mytech.se

**Comment by tinohager** [comment]
Hi, can you try with the new version of `Nager.LicenseSystem` `1.1.0`

**Comment by mytechmicke** [comment]
Hi,
just sent you an email.

**Comment by tinohager** [comment]
The new package now has legacy json support without dependencies. Please also use the updated license key in the sponsor dashboard.
