### ISSUE TITLE
Docker container 2.3.0 not working

### ISSUE THREAD

**Issue by mimenz** [nager/Nager.Date#628]
### Docker TAG

nager/nager-date:latest (2.3.0)

### More information

Pulled the latest docker container (2.3.0), service is not starting:

Stacktrace:
info: Nager.Date.Website[0]
      License valid until 2025-05-10
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:8080
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HN2F5FMBJ633", Request id "0HN2F5FMBJ633:00000001": An unhandled exception was thrown by the application.
      System.InvalidOperationException: The 'OneHour' cache profile is not defined.
         at Microsoft.AspNetCore.Mvc.ResponseCacheAttribute.GetCacheProfile(MvcOptions options)
         at Microsoft.AspNetCore.Mvc.ResponseCacheAttribute.CreateInstance(IServiceProvider serviceProvider)
         at Microsoft.AspNetCore.Mvc.Filters.DefaultFilterProvider.ProvideFilter(FilterProviderContext context, FilterItem filterItem)
         at Microsoft.AspNetCore.Mvc.Filters.DefaultFilterProvider.OnProvidersExecuting(FilterProviderContext context)
         at Microsoft.AspNetCore.Mvc.Filters.FilterFactory.CreateUncachedFiltersCore(IFilterProvider[] filterProviders, ActionContext actionContext, List`1 filterItems)
         at Microsoft.AspNetCore.Mvc.Filters.FilterFactory.GetAllFilters(IFilterProvider[] filterProviders, ActionContext actionContext)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvokerCache.GetCachedResult(ControllerContext controllerContext)
         at Microsoft.AspNetCore.Mvc.Routing.ControllerRequestDelegateFactory.<>c__DisplayClass12_0.<CreateRequestDelegate>b__0(HttpContext context)
         at Nager.Date.Website.Middlewares.ErrorHandlerMiddleware.Invoke(HttpContext context) in /src/Nager.Date.Website/Middlewares/ErrorHandlerMiddleware.cs:line 16
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by tinohager** [comment]
I have push a new version of the Docker, now it should be work

**Comment by mimenz** [comment]
Works!
That was fast, thanks a lot!
